/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class optimisation_coco_CocoJNI */

#ifndef _Included_optimisation_coco_CocoJNI
#define _Included_optimisation_coco_CocoJNI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
